/**
 * GitHub API client helpers.
 * All methods require GITHUB_TOKEN set in the environment.
 */
import { Octokit } from '@octokit/rest';
import { execFile } from 'child_process';
import { promisify } from 'util';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';

const execFilePromise = promisify(execFile);

export interface PrFile {
  /** Repo-relative forward-slash path */
  filename: string;
  /** File content with conflict markers generated by git merge-file */
  content: string;
  /** The blob SHA on the PR head branch — needed when creating a replacement commit */
  blobSha: string;
}

export interface PrInfo {
  /** SHA of the head commit on the PR branch */
  headSha: string;
  /** Branch name that the PR is from */
  headBranch: string;
  /** SHA of the base (target) commit — the common ancestor side */
  baseSha: string;
  /** Whether GitHub considers the PR mergeable */
  mergeable: boolean | null;
}

function getOctokit(): Octokit {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error(
      'GITHUB_TOKEN environment variable is not set. ' +
        'Create a Personal Access Token with repo scope and add it to .env.local.'
    );
  }
  return new Octokit({ auth: token });
}

/** Fetch basic metadata about a pull request. */
export async function getPrInfo(
  owner: string,
  repo: string,
  prNumber: number
): Promise<PrInfo> {
  const octokit = getOctokit();
  const { data } = await octokit.pulls.get({ owner, repo, pull_number: prNumber });
  return {
    headSha: data.head.sha,
    headBranch: data.head.ref,
    baseSha: data.base.sha,
    mergeable: data.mergeable,
  };
}

/** Fetch a file's raw content at a given ref. Returns null if the file doesn't exist at that ref. */
async function fetchFileContent(
  octokit: Octokit,
  owner: string,
  repo: string,
  filePath: string,
  ref: string
): Promise<{ content: string; blobSha: string } | null> {
  try {
    const { data } = await octokit.repos.getContent({ owner, repo, path: filePath, ref });
    if (Array.isArray(data) || data.type !== 'file') return null;

    let content: string;
    if (data.content) {
      content = Buffer.from(data.content, 'base64').toString('utf8');
    } else if (data.download_url) {
      // Large file (>1 MB) — GitHub omits content and provides a raw download URL
      const res = await fetch(data.download_url);
      if (!res.ok) return null;
      content = await res.text();
    } else {
      return null;
    }
    return { content, blobSha: data.sha };
  } catch {
    return null;
  }
}

/**
 * Fetch the raw content of every file in a PR that has merge conflicts,
 * with conflict markers (`<<<<<<<` / `=======` / `>>>>>>>`) generated locally
 * via `git merge-file`.
 *
 * Why not use `refs/pull/N/merge`?
 * GitHub only creates that ref when the PR is auto-mergeable (`mergeable: true`).
 * When there are actual conflicts (`mergeable: false`), the ref does not exist.
 *
 * Strategy:
 *   1. List all files changed in the PR.
 *   2. For each file, fetch the content from the BASE branch and the HEAD branch.
 *   3. Run `git merge-file` with an empty ancestor to produce conflict markers.
 *   4. Keep only files where the merge produced conflicts.
 */
export async function fetchConflictedFiles(
  owner: string,
  repo: string,
  prNumber: number,
  headSha: string,
  baseSha: string
): Promise<PrFile[]> {
  const octokit = getOctokit();

  const { data: prFiles } = await octokit.pulls.listFiles({
    owner,
    repo,
    pull_number: prNumber,
    per_page: 100,
  });

  const results: PrFile[] = [];
  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'gh-merge-'));

  try {
    for (const f of prFiles) {
      if (!f.filename || f.status === 'removed') continue;

      // Fetch the file at both sides
      const [baseFile, headFile] = await Promise.all([
        fetchFileContent(octokit, owner, repo, f.filename, baseSha),
        fetchFileContent(octokit, owner, repo, f.filename, headSha),
      ]);

      // If either side is missing the file was added/removed unilaterally — no conflict
      if (!baseFile || !headFile) continue;

      // If both sides are identical there's nothing to merge
      if (baseFile.content === headFile.content) continue;

      // Write both sides to temp files and run git merge-file
      // We use the base as the "ancestor" AND "ours", head as "theirs" so that
      // any divergence from the base shows up as a conflict.
      const safeBase = f.filename.replace(/\//g, '_');
      const oursPath = path.join(tmpDir, `${safeBase}.ours`);
      const ancestorPath = path.join(tmpDir, `${safeBase}.ancestor`);
      const theirsPath = path.join(tmpDir, `${safeBase}.theirs`);

      await Promise.all([
        fs.writeFile(oursPath, baseFile.content, 'utf8'),
        fs.writeFile(ancestorPath, baseFile.content, 'utf8'),
        fs.writeFile(theirsPath, headFile.content, 'utf8'),
      ]);

      // git merge-file exits 0 (clean), positive N (N conflicts), or negative (error)
      // It writes the result in-place to oursPath
      try {
        await execFilePromise('git', [
          'merge-file',
          '-L', 'HEAD',
          '-L', 'base',
          '-L', 'incoming',
          oursPath,
          ancestorPath,
          theirsPath,
        ]);
        // Exit 0 = no conflicts — the two sides merged cleanly, skip this file
        continue;
      } catch (err: any) {
        // Positive exit code = number of conflict hunks — this is what we want
        if (typeof err.code !== 'number' || err.code <= 0) continue;
      }

      const conflicted = await fs.readFile(oursPath, 'utf8');
      if (!conflicted.includes('<<<<<<<')) continue;

      results.push({ filename: f.filename, content: conflicted, blobSha: headFile.blobSha });
    }
  } finally {
    await fs.rm(tmpDir, { recursive: true, force: true });
  }

  return results;
}

/**
 * Push a single file change as a new commit on the PR branch.
 * Used by the approve flow to write the resolved content back to GitHub.
 */
export async function pushResolvedFile(opts: {
  owner: string;
  repo: string;
  branch: string;
  filePath: string;
  resolvedContent: string;
  blobSha: string;
  commitMessage?: string;
}): Promise<void> {
  const octokit = getOctokit();

  const message =
    opts.commitMessage ??
    `fix: auto-resolve merge conflict in ${opts.filePath} [conflict-resolver]`;

  await octokit.repos.createOrUpdateFileContents({
    owner: opts.owner,
    repo: opts.repo,
    path: opts.filePath,
    message,
    content: Buffer.from(opts.resolvedContent, 'utf8').toString('base64'),
    sha: opts.blobSha,
    branch: opts.branch,
  });
}
